/**
 * Editor + Designs API end-to-end test.
 *
 * Verifies the editor opens a page generated by the API and renders it in
 * Live mode (the round-trip the agent uses — generate → open in editor).
 *
 * Run separately from the main smoke (longer, depends on the API running):
 *   1. start `service/` with OPENROUTER_API_KEY + RHOBEAR_DESIGNS_BYPASS_QUOTA=1
 *   2. npx playwright test tests/e2e/designs-api.spec.js
 *
 * The test uses a small stub HTML page (not a live model call) so it's fast
 * and deterministic. The full generate path is exercised by the API tests
 * + the live "designs-b1" lane, not by this one.
 */
import { test, expect, request } from '@playwright/test';

const API_BASE = process.env.RHOBEAR_DESIGNS_API || 'http://127.0.0.1:8765';
const TOKEN = process.env.RHOBEAR_SERVICE_TOKEN || 'test-token';

const stubHtml = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8" /><title>Agent Page</title>
<style>
  body { font-family: system-ui, sans-serif; margin: 0; padding: 40px; background: #f5f5f5; }
  h1 { color: #1a1a2e; }
  .card { background: #fff; padding: 24px; border-radius: 12px; max-width: 560px; }
</style>
</head>
<body>
  <div class="card">
    <h1>Agent-generated page</h1>
    <p>This page was created by the Designs API and opened in the editor for hand-editing.</p>
  </div>
</body>
</html>`;

let pageId;
test.beforeAll(async () => {
  const ctx = await request.newContext({ baseURL: API_BASE, extraHTTPHeaders: { authorization: `Bearer ${TOKEN}` } });
  // Create a stub page directly via the store by going through /v1/pages/generate
  // would take ~1 min. Instead we use a fresh page_id and write directly to the
  // service data dir through a small helper endpoint... but the service doesn't
  // expose one. The simplest deterministic route: use generate with a tiny
  // prompt and bypass_quota, accept the model call latency (one-time).
  const res = await ctx.post('/v1/pages/generate', {
    data: {
      prompt: 'A clean, simple landing page for a fictional productivity app called "Agent Page". Single hero section with a large H1 "Welcome to Agent Page", a short paragraph explaining the product, and a primary call-to-action button. Modern minimal design with system fonts, white background, blue accent color. Single page, no navigation.',
      workspace_id: 'ws_e2e_designs_api',
    },
  });
  expect(res.status()).toBe(202);
  const { job_id } = (await res.json()).data;
  // Poll.
  let job;
  for (let i = 0; i < 60; i++) {
    const r = await ctx.get(`/v1/jobs/${job_id}`);
    job = (await r.json()).data;
    if (job.status === 'succeeded' || job.status === 'failed') break;
    await new Promise((r) => setTimeout(r, 2000));
  }
  expect(job.status, 'generate job should succeed').toBe('succeeded');
  pageId = job.result.page_id;
  expect(pageId).toBeTruthy();
});

test('editor opens a page from the Designs API via ?designs_page_id', async ({ page }) => {
  // The dev server is on 5180 (Playwright config). The API is on 8765
  // (default). They run on different origins so we tell the editor where the
  // API is via the ?designs_api= query param.
  await page.goto(`/?designs_page_id=${pageId}&designs_api=${encodeURIComponent(API_BASE + '/v1')}`);

  // The editor's autoLoadFromApi kicks off a fetch — wait for the title to be set.
  await page.waitForFunction(() => window.__RB_EDITOR__?.ready);
  await page.waitForFunction(() => {
    const t = document.getElementById('doc-title');
    return t && t.textContent && !t.textContent.includes('Untitled');
  }, { timeout: 15_000 });

  // Live-frame iframe should have loaded the page html.
  const frame = page.frameLocator('[data-testid="live-frame"]');
  await expect(frame.locator('h1').first()).toBeVisible({ timeout: 10_000 });
});

test('envelope: the page is visible inside the live iframe with the API-loaded content', async ({ page }) => {
  await page.goto(`/?designs_page_id=${pageId}&designs_api=${encodeURIComponent(API_BASE + '/v1')}`);
  await page.waitForFunction(() => window.__RB_EDITOR__?.ready);
  const frame = page.frameLocator('[data-testid="live-frame"]');
  await expect(frame.locator('h1').first()).toBeVisible({ timeout: 10_000 });
  // Body should not be empty.
  await expect(frame.locator('body')).not.toBeEmpty();
});

test('the editor can hand-edit the API-loaded page (click an element → inspector opens)', async ({ page }) => {
  await page.goto(`/?designs_page_id=${pageId}&designs_api=${encodeURIComponent(API_BASE + '/v1')}`);
  await page.waitForFunction(() => window.__RB_EDITOR__?.ready);
  const frame = page.frameLocator('[data-testid="live-frame"]');
  const h1 = frame.locator('h1').first();
  await h1.waitFor();
  await h1.click();
  await expect(page.getByTestId('inspector')).not.toHaveClass(/is-hidden/);
});