/**
 * Local file import/export — browser File API + JSZip.
 * MIT — RHOBEAR Designs (original)
 */

import { saveAs } from 'file-saver';
import JSZip from 'jszip';
import { wrapExportedHtml, parseImportedHtml } from './serializer.js';

export class FileIO {
  constructor(editor) {
    this.editor = editor;
    this.assetMap = new Map();
    this.docTitle = 'Untitled page';
  }

  setTitle(title) {
    this.docTitle = title || 'Untitled page';
    const el = document.getElementById('doc-title');
    if (el) el.textContent = this.docTitle;
  }

  newProject() {
    const ed = this.editor;
    ed.setComponents('');
    ed.setStyle('');
    ed.UndoManager.clear();
    this.assetMap.clear();
    this.setTitle('Untitled page');
    this.setStatus('New blank page');
  }

  async loadHtmlFile(file) {
    const text = await file.text();
    const parsed = parseImportedHtml(text);
    this.applyImport(parsed);
    this.setTitle(parsed.title || file.name.replace(/\.html?$/i, ''));
    this.setStatus(`Loaded ${file.name}`);
  }

  async loadFolder(files) {
    const fileList = [...files];
    this.assetMap.clear();

    let htmlFile = fileList.find((f) => /\.html?$/i.test(f.name));
    if (!htmlFile) {
      htmlFile = fileList.find((f) => f.name.toLowerCase() === 'index.html');
    }
    if (!htmlFile) {
      throw new Error('No .html file found in folder');
    }

    const basePath = htmlFile.webkitRelativePath.replace(/[^/]+$/, '');

    for (const f of fileList) {
      const rel = f.webkitRelativePath.replace(basePath, '');
      if (rel && !f.name.endsWith('.html') && !f.name.endsWith('.htm')) {
        const url = URL.createObjectURL(f);
        this.assetMap.set(rel, url);
        this.assetMap.set(f.name, url);
      }
    }

    let htmlText = await htmlFile.text();

    for (const [path, url] of this.assetMap) {
      const escaped = path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      htmlText = htmlText.replace(new RegExp(`(src|href)=["'](\\.?/?)${escaped}["']`, 'gi'), `$1="${url}"`);
      htmlText = htmlText.replace(new RegExp(`url\\(['"]?(\\.?/?)${escaped}['"]?\\)`, 'gi'), `url('${url}')`);
    }

    const parsed = parseImportedHtml(htmlText);
    this.applyImport(parsed);
    this.setTitle(htmlFile.name.replace(/\.html?$/i, ''));
    this.setStatus(`Loaded folder (${fileList.length} files)`);
  }

  applyImport({ html, css }) {
    const ed = this.editor;
    ed.setComponents(html || '<div class="container"><h1>New page</h1></div>');
    if (css) ed.setStyle(css);
    ed.UndoManager.clear();
  }

  getExportPayload() {
    const ed = this.editor;
    return {
      html: ed.getHtml(),
      css: ed.getCss(),
      title: this.docTitle,
    };
  }

  saveHtml() {
    const payload = this.getExportPayload();
    const full = wrapExportedHtml(payload);
    const blob = new Blob([full], { type: 'text/html;charset=utf-8' });
    const filename = slugify(payload.title) + '.html';
    saveAs(blob, filename);
    this.setStatus(`Saved ${filename}`);
  }

  async exportZip() {
    const payload = this.getExportPayload();
    const zip = new JSZip();
    const base = slugify(payload.title);

    const htmlDoc = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${payload.title}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
${payload.html || ''}
</body>
</html>`;

    zip.file('index.html', htmlDoc);
    zip.file('styles.css', payload.css || '/* Generated by RHOBEAR Designs */');

    const assets = zip.folder('assets');
    for (const [name, url] of this.assetMap) {
      try {
        const res = await fetch(url);
        const blob = await res.blob();
        assets.file(name.split('/').pop(), blob);
      } catch {
        /* skip broken asset refs */
      }
    }

    const out = await zip.generateAsync({ type: 'blob' });
    saveAs(out, `${base}.zip`);
    this.setStatus(`Exported ${base}.zip`);
  }

  setStatus(msg) {
    const el = document.getElementById('status-message');
    if (el) el.textContent = msg;
  }
}

function slugify(str) {
  return String(str)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'page';
}